```java
Integer num = Integer.valueOf(100);
Integer num2 = Integer.valueOf(100);
System.out.println(num == num2); // true
// Integer.valueOf 메소드는 값을 가리키는 객체가 없으면 새로 만들고
// 있다면 같은 참조를 가리켜 메모리를 절약한다
```

# Exception (예외)
- 런타임에러가 발생했을 때
```
Exception in thread "main" java.util.InputMismatchException
// 예외가 발생했다. 입력이 맞지 않다.
	at java.base/java.util.Scanner.throwFor(Scanner.java:939)
	at java.base/java.util.Scanner.next(Scanner.java:1594)
	at java.base/java.util.Scanner.nextInt(Scanner.java:2258)
	at java.base/java.util.Scanner.nextInt(Scanner.java:2212)
	at _241122_exception_try_catch.Main.main(Main.java:10)
	// Main.java.:10번째 라인에서 예외가 발생했다
```
```java
import java.util.InputMismatchException;
// 예외도 하나의 클래스이기 때문에 참조해야한다

try {
	System.out.print("1: ");
	int first = scan.nextInt();
	System.out.print("2: ");
	int second = scan.nextInt();
	if (second != 0) {
		int divide = first / second;
		System.out.println("answer: " + divide);
	} else {
		System.out.println("0으로 나눌 수 없다");
	}
	// 에러발생 시점만이 아니라 정상적인 흐름의 코드가 전부 try 내부에 위치해야한다
} catch (InputMismatchException e) {
	System.out.println("정수로 넣어라")
	// 에러로 프로그램이 종료되지 않고 에러임을 알리고 정상흐름으로 돌아감
}
```
```java
// 정상적인 입력이 올때까지 반복하는 코드의 예
while (true) {
	try {
		return SCAN.nextInt();
		// 정상적인 입력을 받으면 리턴한다
	} catch (InputMismatchException e) {
		SCAN.nextLine(); // 입력 버퍼 비우기
		// 정상적인 입력이 들어올 때까지 반복하게 된다
		System.out.println("정수를 넣어라");
		// 사용자에게 문제를 알린다
	}
}
```
- 예외 발생한 라인을 확인하고 제어가능한 상황이라면 코드 수정을 한다
### 예외처리
```java
public int getElement(int[] arr, int index) {
	if (index >= 0 && index < arr.length) {
		return arr[index];
		// 조건부 반환이기 때문에 컴파일에러가 발생한다
	}
	throw new RuntimeException("인덱스 범위 밖.");
	// 임의의 예외상황을 만들어서 쳐내는 키워드 : throw
	// try-catch를 사용해 예외처리를 한다
}
```

Throwable
- **Error**
- **Exception**
	- **Runtime Exception** (unchecked Exception : *개발자가 체크* )
		- ArithmaeticException
		- NullPointerException
		- ArrayIndexOutOfBoundsException
	- **checked Exception** (컴파일단계에서 체크)
		- ClassNotFoundException
		- IOException
		- InterrupedException
		- SQLException
		- FileNotFoundException

```java
int local;
try {
	local = 10;
} catch (Exception e) {
	System.out.println(local); // 컴파일에러: local의 초기화가 안될 가능성 존재
}
```
```java
public int num() {
	try {
		return 100;
	} finally {
	System.out.println("can't reach");
	// 리턴을 하고 나서도 반드시 실행한다
	}
}
```
**e.printStackTrace()**
개발자가 실행 흐름을 추적할 수 있도록 콘솔에 출력해준다

```java
try {
	scan.nextInt();
} catch (InputMismatchException e) {
	// 예외 타입이 일치하지 않으면 예외가 그대로 발생한다
	// 예외 타입을 부모형으로 지정해두면 자식형의 예외를 catch한다
	// Exception(최상위예외) > RuntimeException > InputMismathchException
	System.out.println("예외 메세지: " + e.getMessage());
	e.printStackTrace();
	System.out.println("정수가 아님");
}
```
```java
if (amount > 0) {
	this.balance += amount;
} else {
	throw new RuntimeException("음수는 안돼");
}
// 예외를 임의로 발생시켜서 상위 메소드로 던진다
try {
	account.deposit(10000);
	account.withdraw(3000);
} catch (RuntimeException e) {
	System.out.println("런타임 에러요");
} // 다중 catch도 가능하며 자식예외가 먼저 오고 부모예외가 오도록 한다
// 발생한 예외를 잡아서 예외메세지를 출력한다
```
```java
try {
	account.deposit(10000);
	account.withdraw(3000);
} catch (MinusAmountException e) {
	System.out.println(e.getMessage());
} catch (NotEnoughBalanceException e) {
	System.out.println(e.getMessage());
} catch (RuntimeException e) {
	System.out.println("런타임 에러요");
} // 다중 catch도 가능하며 자식예외가 먼저 오고 부모예외가 오도록 한다

try {
	account.deposit(10000);
	account.withdraw(3000);
} catch (MinusAmountException | NotEnoughBalanceException e) {
	System.out.println(e.getMessage());
	// 서로 다른 예외가 처리법이 같다면 | 를 사용하여 하나의 블럭으로 묶을 수 있다
} catch (RuntimeException e) {
	System.out.println("런타임 에러요");
}
```

# Summary
1. Error, Exception의 상위 부모 클래스는?
	- Throwable 클래스
2. JVM에서 프로그램 실행 중 예외가 발생 되었을 때, call stack에 예외 처리 구조가 존재하지 않을 때는 어떤 일이 일어나는가?
	- 예외가 발생한 위치를 출력하고(call stack trace) 프로그램을 강제종료한다 
3. Java에서 강제적 예외 처리 구조를 요구하는 예외 타입은 어떤 클래스를 상속한 예외인가? 명칭은?
	- checked Exception 이라고 하고 Exception 클래스를 상속한다
4. 실행 중 예외를 의미하는 클래스로, unchecked 예외의 부모 클래스는?
	- RuntimeException
5. try - catch 또는 try 블럭에서 마지막 실행을 보장받는 문장을 적으려면?
	- finally 블럭을 생성하고 블럭 내부에 코드를 작성한다
6. 여러 개의 catch 블럭을 구성할 때 주의점?
	- 자식예외를 먼저 작성하고 부모예외를 작성한다
	- 그렇지 않으면 부모예외에서 모든 예외가 잡히므로 컴파일에러가 발생한다
7. 예외 객체를 생성해 던지는 방법은?
	 1. throw 키워드를 사용해 상위메소드로 돌려보낸다
	 2. 예외객체를 임의로 작성할 수도 있고 임의로 작성한 예외로 던져보내는 것도 가능하다